# Generated by Django 5.2.7 on 2025-12-10 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
