# Generated by Django 5.2.7 on 2025-12-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTRELAS', 'Estrelas'), ('PLANETAS', 'Planetas'), ('GALAXIAS', 'Galáxias'), ('NEBULOSAS', 'Nebulosas')], default='', max_length=100),
        ),
    ]
